### ISSUE TITLE
I have rJava installed and runned the `chmod +x` command but still wasn't able to get the pathway information that I wanted. 

### ISSUE THREAD

**Issue by garyzhubc** [PavlidisLab/ermineR#24] opened 2023-12-01 16:28 UTC
I have rJava installed and runned the `chmod +x` command but still wasn't able to get the pathway information that I wanted. 

```
> oraOut <- ora(annotation = 'Generic_human', hitlist = hitlist)
Attempting to download annotation file
Error in (function (annotation = NULL, aspects = c("Molecular Function",  : 
  Something went wrong. Blame the dev
INFO: Data directory is /Users/garyzhubc/ermineJ.data
DEBUG: Custom gene sets directory is /Users/garyzhubc/ermineJ.data/genesets
DEBUG: Setting score start column to 2
INFO: Gene symbols for each term will be output
DEBUG: gene score threshold set to 0.5
Reading GO descriptions from /var/folders/w8/9_5f04c54b585y1kjq898d180000gn/T/RtmpCygyvd/file134597a7acf02 ... 
Reading gene annotations from /var/folders/w8/9_5f04c54b585y1kjq898d180000gn/T/RtmpCygyvd/file1345963d035c7 ... 
WARN: Duplicated element: NPHP3-ACAD11 at line 1435, skipping
Read 2500 elements ... 
WARN: Duplicated element: RNASEK-C17ORF49 at line 4697, skipping
Read 5000 elements ... 
WARN: Duplicated element: INO80B-WBP1 at line 5032, skipping
WARN: Duplicated element: C1QTNF3-AMACR at line 5148, skipping
WARN: Duplicated element: FLJ45825 at line 5673, skipping
Read 7500 elements ... 
WARN: Duplicated element: ARHGAP19-SLIT1 at line 7721, skipping
WARN: Duplicated element: DUX
```

**Comment by oganm** [comment] 2023-12-04 23:18
Would you mind showing what the hitlist was?

**Comment by oganm** [comment] 2023-12-04 23:42
Actually nevermind, the problem is on our side. ermineR uses annotation files provided by Gemma to access go terms, however our databases do not have the terms loaded right now. 

This issue should be fixed soon however in the meanwhile you can create your own annotation file by doing

```r
library('org.Hs.eg.db') # get go terms from bioconductor 

goAnnots = as.list(org.Hs.egGO)
goAnnots = goAnnots %>% lapply(names)

geneSymbols = as.list(org.Hs.egSYMBOL) %>% unlist
geneName = as.list(org.Hs.egGENENAME) %>% unlist

annotation = makeAnnotation(goAnnots,
                            symbol = geneSymbols,
                            name = geneName,
                            output = NULL, # you can choose to save the annotation to a file
                            return = TRUE)
```

note that this annotation will work if the hitlist is ncbi ids. if you'd want to use symbols do this after:

```r
annotation$IDs = annotation$GeneSymbols
```

**Closed as completed** 2024-09-19 20:13 UTC
